'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=v=>v!==null&&v!==''&&Number.isFinite(Number(v));
const n=(v,d=1)=>finite(v)?Number(v).toFixed(d):'—';
const pct=(v,d=1)=>finite(v)?`${Number(v)>=0?'+':''}${Number(v).toFixed(d)}%`:'—';
const median=a=>{const x=a.filter(finite).map(Number).sort((a,b)=>a-b); if(!x.length)return NaN; const m=Math.floor(x.length/2); return x.length%2?x[m]:(x[m-1]+x[m])/2};
const mean=a=>{const x=a.filter(finite).map(Number);return x.length?x.reduce((s,v)=>s+v,0)/x.length:NaN};
const load=async u=>{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`${u}: HTTP ${r.status}`);return r.json()};
const loadSiteData=async()=>{const meta=await load('data/site-meta.json');const chunks=await Promise.all((meta.record_files||[]).map(load));return {...meta,records:chunks.flat()}};
const MODELS={
 balanced:{label:'Balanced',zh:'平衡型',desc:'均衡配置五因子',w:{profitability:.27,financial_strength:.22,forward_growth:.22,earnings_revision:.16,valuation:.13}},
 quality:{label:'Quality',zh:'品質型',desc:'偏重獲利品質與財務穩健',w:{profitability:.40,financial_strength:.30,forward_growth:.10,earnings_revision:.10,valuation:.10}},
 growth:{label:'Growth',zh:'成長型',desc:'偏重前瞻成長',w:{profitability:.15,financial_strength:.10,forward_growth:.40,earnings_revision:.25,valuation:.10}},
 earnings:{label:'Earnings Momentum',zh:'盈餘動能型',desc:'偏重盈餘預期修正',w:{profitability:.15,financial_strength:.10,forward_growth:.25,earnings_revision:.40,valuation:.10}},
 garp:{label:'GARP',zh:'GARP',desc:'成長與合理估值並重',w:{profitability:.20,financial_strength:.15,forward_growth:.30,earnings_revision:.15,valuation:.20}}
};
const FACTORS={profitability:'獲利能力',financial_strength:'財務穩健',forward_growth:'前瞻成長',earnings_revision:'盈餘修正',valuation:'相對估值'};
const DATASET_LABEL={universe_web:'正式研究母體',price_momentum:'價格 / Momentum',risk_90d:'Risk 90D',comparison_metrics:'相對估值資料',earnings_revision:'盈餘修正',current_forward_pe:'Current Forward P/E'};
const state={data:null,official:null,snapshot:null,manifest:null,records:[],view:'overview',rank:{query:'',model:'consensus',scale:'formal',status:'ALL',industry:'ALL',sort:'rank',dir:1},compare:[],commandIndex:0};

function modelStatus(r){return r.quality?.model_status||(r.quality?.model_not_due?'NOT_DUE':r.quality?.model_ready?'READY':'UNRESOLVED')}
function industry(r){return r.taxonomy?.subindustry||r.taxonomy?.industry||r.taxonomy?.sector||'未分類'}
function sector(r){return r.taxonomy?.sector||'未分類'}
function factor(r,k){return r.factors?.[k]?.value}
function valuationMethod(r){return r.valuation?.method||r.valuation?.reason||'—'}
function isTechnology(r){return r._officialPool==='T'}
function decodeSitePayload(payload,snapshot){
  if(!payload||payload.dataset!=='forward_alpha_site_compact'||payload.schema_version!==3||!Array.isArray(payload.records))throw new Error('網站 compact payload 格式錯誤');
  const d=payload.dictionaries||{},sectors=d.sectors||[],industries=d.industries||[],subs=d.subindustries||[],methods=d.valuation_methods||[];
  if(payload.record_count!==payload.records.length||payload.record_count!==Number(snapshot.universe_count||snapshot.formal_universe))throw new Error('Compact payload 與 Snapshot Universe 數量不一致');
  const records=[],officialRecords=[];
  for(const row of payload.records){
    if(!Array.isArray(row)||row.length<24)throw new Error('Compact record 欄位不足');
    const [ticker,company,sectorI,industryI,subI,pool,profitability,financialStrength,forwardGrowth,earningsRevision,valuation,momentum,comparableMomentum,compBalanced,compQuality,compGrowth,compEarnings,compGarp,ret3,ret6,ret12,currentPe,evEbitda,methodI]=row;
    const returns=[ret3,ret6,ret12],full=returns.every(v=>v!==null&&v!=='');
    records.push({ticker,company,taxonomy:{sector:sectors[sectorI]||'',industry:industries[industryI]||'',subindustry:subs[subI]||''},factors:{profitability:{value:profitability,status:'READY',reason:''},financial_strength:{value:financialStrength,status:'READY',reason:''},forward_growth:{value:forwardGrowth,status:'READY',reason:''},earnings_revision:{value:earningsRevision,status:'READY',reason:''},valuation:{value:valuation,status:'READY',reason:''}},momentum:{ret_3m:ret3,ret_6m:ret6,ret_12m:ret12,weights:{ret_3m:.15,ret_6m:.35,ret_12m:.50},status:'READY',history_status:full?'FULL_READY':'PARTIAL_READY',history_age_days:null,partial_real_renormalization:!full,reason:full?'FULL_3M_6M_12M_HISTORY':'PARTIAL_HISTORY; SCORE_FROM_PRODUCTION_OUTPUT',score_eligible:true,web_valid:true},quality:{model_ready:true,model_not_due:false,model_status:'READY',not_due:[],blockers:[],web_complete:true},risk:{std_dev_90d:null,downside_dev_90d:null,risk_score:null,role:'REPORT_ONLY',status:'NOT_EXPOSED',source_status:'NOT_EXPOSED_IN_PRODUCTION_XLSX',source_series:'',reason:'PRODUCTION_XLSX_DOES_NOT_EXPOSE_90D_RISK_VALUES_FOR_THIS_SNAPSHOT'},valuation:{method:methods[methodI]||'',status:'READY',current_forward_pe:currentPe,ev_ebitda:evEbitda,reason:currentPe===null?'Current Forward P/E 尚未補齊；不影響正式 Universe':'Current Forward P/E 已有資料'}});
    officialRecords.push([ticker,pool,momentum,comparableMomentum,compBalanced,compQuality,compGrowth,compEarnings,compGarp]);
  }
  return {data:{schema_version:3,dataset:'universe_web',membership_source:payload.membership_source,universe_count:payload.record_count,formal_universe:payload.record_count,technology_count:payload.technology_count,outside_count:payload.outside_count,model_ready:payload.record_count,model_not_due:0,model_resolved:payload.record_count,model_unresolved:0,web_complete:payload.record_count,publish_ready:true,production_model_changed:false,blockers:[],blocker_summary:{},records},official:{schema_version:3,dataset:'official_model_universe_compact',market_key:snapshot.market_key,membership_source:payload.membership_source,record_count:payload.record_count,technology_count:payload.technology_count,outside_count:payload.outside_count,model_order:payload.model_order,records:officialRecords}};
}
function alphaFromFactors(r,model){let total=0;for(const [k,w] of Object.entries(MODELS[model].w)){const v=factor(r,k);if(!finite(v))return NaN;total+=Number(v)*w}return total}
function consensusFrom(models){const alphas=Object.values(models).map(x=>x.alpha),sels=Object.values(models).map(x=>x.selection);return {alpha:median(alphas),selection:median(sels),divergence:Math.max(...sels)-Math.min(...sels)}}
function enrich(records,official){
  if(!official||official.dataset!=='official_model_universe_compact'||!Array.isArray(official.records)||official.record_count!==official.records.length||official.record_count!==records.length)throw new Error('正式五模型資料與 Active Universe 數量不一致');
  if(official.market_key!==state.snapshot.market_key)throw new Error(`正式五模型 Market Key 不一致：${official.market_key} / ${state.snapshot.market_key}`);
  const order=official.model_order||[],expected=Object.keys(MODELS);if(order.join('|')!==expected.join('|'))throw new Error('正式五模型順序不一致');
  const map=new Map(official.records.map(x=>[x[0],x]));if(map.size!==official.records.length)throw new Error('正式五模型 Ticker 有重複');
  const missing=records.filter(r=>!map.has(r.ticker)).map(r=>r.ticker),baseTickers=new Set(records.map(r=>r.ticker)),extra=official.records.filter(x=>!baseTickers.has(x[0])).map(x=>x[0]);
  if(missing.length||extra.length)throw new Error(`正式五模型 Ticker 集合不一致：missing=${missing.join(',')} extra=${extra.join(',')}`);
  for(const r of records){
    const row=map.get(r.ticker),pool=row[1],momentum=Number(row[2]),comparableMomentum=Number(row[3]);
    if(!['T','O'].includes(pool)||!finite(momentum)||!finite(comparableMomentum))throw new Error(`${r.ticker} 正式 Momentum / Pool 資料缺失`);
    r._officialPool=pool;r._momentum=momentum;r._comparable={momentum:comparableMomentum};r._models={formal:{},comparable:{}};
    expected.forEach((m,i)=>{
      const formalAlpha=alphaFromFactors(r,m),compAlpha=Number(row[4+i]);
      if(!finite(formalAlpha)||!finite(compAlpha))throw new Error(`${r.ticker} ${m} 正式 Alpha 缺失`);
      r._models.formal[m]={alpha:formalAlpha,selection:.7*formalAlpha+.3*momentum};
      r._models.comparable[m]={alpha:compAlpha,selection:.7*compAlpha+.3*comparableMomentum};
    });
    r._models.formal.consensus=consensusFrom(r._models.formal);r._models.comparable.consensus=consensusFrom(r._models.comparable);
  }
  const tech=records.filter(isTechnology).length,outside=records.length-tech;if(tech!==official.technology_count||outside!==official.outside_count)throw new Error(`正式分析池數量不一致：Technology ${tech}, Outside ${outside}`);
  assignRanks(records,'formal');assignRanks(records,'comparable');
}
function assignRanks(records,scale){for(const m of [...Object.keys(MODELS),'consensus']){const arr=records.filter(r=>finite(r._models[scale][m].selection)).sort((a,b)=>b._models[scale][m].selection-a._models[scale][m].selection);arr.forEach((r,i)=>r._models[scale][m].rank=i+1)}}
function switchView(id){state.view=id;$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('#mainNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'instant'})}
function pillStatus(s){return `<span class="pill ${s==='READY'?'ok':s==='NOT_DUE'?'warn':'bad'}">${esc(s)}</span>`}
function metric(label,value,sub=''){return `<div class="metric-card"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(sub)}</small></div>`}
function renderOverview(){const s=state.snapshot,rs=state.records;$('#snapshotMeta').innerHTML=`Market Key <b>${esc(s.market_key)}</b><br>Snapshot R${s.snapshot_revision} · ${esc(String(s.model_policy||'').split('.').pop())}`;const tech=rs.filter(isTechnology).length;$('#overviewMetrics').innerHTML=[metric('正式母體',`${rs.length}`,'Mapping Active Universe'),metric('READY',`${s.model_ready}`,'可完整比較'),metric('NOT_DUE',`${s.model_not_due}`,'新上市歷史累積中'),metric('Technology View',`${tech}`,'Mapping Bucket 1.1'),metric('Web Complete',`${s.web_complete}/${rs.length}`,`${state.data.blockers.length} blockers`)].join('');renderLeaderList('#consensusLeaders',rs,'consensus','formal',8);const modelRows=Object.entries(MODELS).map(([k,m])=>{const top=rs.filter(r=>finite(r._models.formal[k].selection)).sort((a,b)=>b._models.formal[k].selection-a._models.formal[k].selection)[0];return `<div class="model-snap-row" data-ticker="${top.ticker}"><b>${m.zh}<span class="subtext">${m.label}</span></b><div class="bar"><i style="width:${Math.max(0,Math.min(100,top._models.formal[k].selection))}%"></i></div><strong>${n(top._models.formal[k].selection)}</strong></div>`}).join('');$('#modelSnapshot').innerHTML=modelRows;$('#freshnessGrid').innerHTML=state.manifest.sources.map(x=>`<div class="fresh-card"><b>${esc(DATASET_LABEL[x.dataset]||x.dataset)}</b><div><span>As-of</span><strong>${esc(x.as_of||'—')}</strong></div><div><span>Coverage</span><strong>${finite(x.coverage)?Math.round(x.coverage*100)+'%':'—'}</strong></div><div><span>狀態</span><strong>${esc(x.freshness_status||'—')}</strong></div><small>${esc(x.cadence||'')} · ${esc(x.freshness_rule||'')}</small></div>`).join('');renderIndustryOverview()}
function renderLeaderList(sel,records,model='consensus',scale='formal',limit=10){const arr=records.filter(r=>finite(r._models[scale][model].selection)).sort((a,b)=>b._models[scale][model].selection-a._models[scale][model].selection).slice(0,limit);$(sel).innerHTML=arr.map((r,i)=>`<div class="leader-row" data-ticker="${esc(r.ticker)}"><span class="ranknum">${i+1}</span><div><span class="ticker-link">${esc(r.ticker)}</span><span class="subtext">${esc(r.company)} · ${esc(industry(r))}</span></div><div><span class="mini-label">Alpha</span><span class="score">${n(r._models[scale][model].alpha)}</span></div><div><span class="mini-label">Momentum</span><span class="score">${n(scale==='formal'?r._momentum:r._comparable.momentum)}</span></div><div><span class="mini-label">Selection</span><span class="score orange">${n(r._models[scale][model].selection)}</span></div></div>`).join('')}
function renderIndustryOverview(){const groups=groupStats(state.records).slice(0,18);const max=Math.max(...groups.map(x=>x.count));$('#industryOverview').innerHTML=groups.map(x=>`<div class="industry-row"><span class="name" title="${esc(x.name)}">${esc(x.name)}</span><div class="bar"><i style="width:${x.count/max*100}%"></i></div><span class="count">${x.count}</span><span class="avg">${n(x.consensus)}</span></div>`).join('')}
function groupStats(records){const m=new Map();for(const r of records){const k=industry(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return [...m].map(([name,rs])=>({name,count:rs.length,consensus:mean(rs.map(r=>r._models.formal.consensus.selection)),rs})).sort((a,b)=>b.count-a.count)}
function fillControls(){const modelOpts=[['consensus','五模型共識'],...Object.entries(MODELS).map(([k,v])=>[k,`${v.zh} / ${v.label}`])];for(const id of ['rankModel','modelLabSelect'])$('#'+id).innerHTML=modelOpts.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');$('#modelLabSelect').value='balanced';const inds=[...new Set(state.records.map(industry))].sort((a,b)=>a.localeCompare(b,'zh-Hant'));$('#rankIndustry').innerHTML='<option value="ALL">全部子產業</option>'+inds.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function rankingData(){const q=state.rank.query.trim().toLowerCase(),model=state.rank.model,scale=state.rank.scale,exactTicker=q&&state.records.some(r=>r.ticker.toLowerCase()===q);let arr=state.records.filter(r=>(!q||(exactTicker?r.ticker.toLowerCase()===q:`${r.ticker} ${r.company} ${industry(r)} ${sector(r)}`.toLowerCase().includes(q)))&&(state.rank.status==='ALL'||modelStatus(r)===state.rank.status)&&(state.rank.industry==='ALL'||industry(r)===state.rank.industry)).map(r=>({r,rank:r._models[scale][model].rank??999,ticker:r.ticker,company:r.company,industry:industry(r),alpha:r._models[scale][model].alpha,momentum:scale==='formal'?r._momentum:r._comparable.momentum,selection:r._models[scale][model].selection,divergence:r._models[scale].consensus.divergence,status:modelStatus(r)}));const k=state.rank.sort,dir=state.rank.dir;arr.sort((a,b)=>{let av=a[k],bv=b[k];if(typeof av==='string'||typeof bv==='string')return String(av??'').localeCompare(String(bv??''),'zh-Hant')*dir;av=finite(av)?Number(av):Infinity;bv=finite(bv)?Number(bv):Infinity;return (av-bv)*dir});return arr}
function renderRankings(){const arr=rankingData();$('#rankingRows').innerHTML=arr.map(x=>`<tr data-ticker="${esc(x.ticker)}"><td>${x.rank===999?'—':x.rank}</td><td class="ticker-cell">${esc(x.ticker)}</td><td>${esc(x.company)}</td><td>${esc(x.industry)}</td><td class="num">${n(x.alpha)}</td><td class="num">${n(x.momentum)}</td><td class="num"><b>${n(x.selection)}</b></td><td class="num">${n(x.divergence)}</td><td>${pillStatus(x.status)}</td></tr>`).join('');$('#rankingCount').textContent=`${arr.length} / ${state.records.length} 檔`;$('#rankingFoot').textContent=`尺度：${state.rank.scale==='formal'?'正式尺度':'跨產業可比尺度'} · 模型：${state.rank.model==='consensus'?'五模型共識':MODELS[state.rank.model].zh} · 排序：${state.rank.sort} ${state.rank.dir===1?'↑':'↓'}`}
function renderPool(view){const records=state.records.filter(view==='technology'?isTechnology:r=>!isTechnology(r));const id=view==='technology'?'technologyContent':'outsideContent';$(view==='technology'?'#techCount':'#outsideCount').textContent=`${records.length} 檔`;const top=records.filter(r=>finite(r._models.formal.consensus.selection)).sort((a,b)=>b._models.formal.consensus.selection-a._models.formal.consensus.selection).slice(0,30);const factorStats=Object.entries(FACTORS).map(([k,l])=>({l,v:mean(records.map(r=>factor(r,k)))}));$('#'+id).innerHTML=`<div class="pool-summary">${metric('標的數',records.length,view==='technology'?'Mapping Bucket 1.1':'Mapping Bucket 1.0')}${metric('READY',records.filter(r=>modelStatus(r)==='READY').length,'model ready')}${metric('共識平均',n(mean(records.map(r=>r._models.formal.consensus.selection))),'Selection')}${metric('子產業',new Set(records.map(industry)).size,'分類數')}</div><div class="pool-layout"><article class="panel no-top pool-table"><div class="panel-head"><div><h2>研究排名 Top 30</h2><p>點 Ticker 開啟完整個股 Detail</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Ticker</th><th>公司</th><th>子產業</th><th class="num">共識 Alpha</th><th class="num">Momentum</th><th class="num">共識 Selection</th><th class="num">分歧</th></tr></thead><tbody>${top.map((r,i)=>`<tr data-ticker="${esc(r.ticker)}"><td>${i+1}</td><td class="ticker-cell">${esc(r.ticker)}</td><td>${esc(r.company)}</td><td>${esc(industry(r))}</td><td class="num">${n(r._models.formal.consensus.alpha)}</td><td class="num">${n(r._momentum)}</td><td class="num"><b>${n(r._models.formal.consensus.selection)}</b></td><td class="num">${n(r._models.formal.consensus.divergence)}</td></tr>`).join('')}</tbody></table></div></article><aside class="side-card"><h3>平均因子</h3>${factorStats.map(x=>`<div class="factor-stat"><div><span>${x.l}</span><b>${n(x.v)}</b></div><div class="bar"><i style="width:${Math.max(0,Math.min(100,x.v))}%"></i></div></div>`).join('')}</aside></div>`}
function renderModels(){const records=state.records;$('#modelCards').innerHTML=Object.entries(MODELS).map(([k,m])=>{const avg=mean(records.map(r=>r._models.formal[k].selection));return `<article class="model-card"><span class="kicker">${m.label}</span><h3>${m.zh}</h3><p>${m.desc}</p>${Object.entries(m.w).map(([f,w])=>`<div class="weight-line"><span>${f==='profitability'?'P':f==='financial_strength'?'F':f==='forward_growth'?'G':f==='earnings_revision'?'R':'V'}</span><div class="bar"><i style="width:${w*100}%"></i></div><b>${Math.round(w*100)}%</b></div>`).join('')}<div class="model-stat"><span>母體平均 Selection</span><b>${n(avg)}</b></div></article>`}).join('');renderModelLab();const arr=records.filter(r=>finite(r._models.formal.consensus.selection)).sort((a,b)=>a._models.formal.consensus.divergence-b._models.formal.consensus.divergence).slice(0,12);$('#modelAgreement').innerHTML=`<div class="agreement-grid">${arr.map(r=>{const top3=Object.keys(MODELS).sort((a,b)=>r._models.formal[b].selection-r._models.formal[a].selection).slice(0,3);return `<div class="agreement-row" data-ticker="${r.ticker}"><b>${r.ticker}</b><div class="agree-dots">${Object.keys(MODELS).map(k=>`<i class="${top3.includes(k)?'on':''}" title="${MODELS[k].zh}"></i>`).join('')}</div><span>共識 ${n(r._models.formal.consensus.selection)}</span><span>分歧 ${n(r._models.formal.consensus.divergence)}</span></div>`}).join('')}</div>`}
function renderModelLab(){const m=$('#modelLabSelect').value||'balanced';renderLeaderList('#modelTopList',state.records,m,'formal',15)}
function renderCompare(){const selected=state.compare.map(t=>state.records.find(r=>r.ticker===t)).filter(Boolean);$('#compareCounter').textContent=`${selected.length} / 4`;$('#compareChips').innerHTML=selected.map(r=>`<span class="chip">${r.ticker}<button data-remove="${r.ticker}">×</button></span>`).join('');$('#compareEmpty').classList.toggle('hidden',selected.length>=2);$('#compareContent').classList.toggle('hidden',selected.length<2);if(selected.length<2)return;const rows=[];const add=(label,vals,section=false,fmt=x=>n(x))=>rows.push({label,vals,section,fmt});add('五模型',[],true);for(const [k,m] of Object.entries(MODELS)){add(`${m.zh} Alpha`,selected.map(r=>r._models.formal[k].alpha));add(`${m.zh} Selection`,selected.map(r=>r._models.formal[k].selection))}add('共識與模型差異',[],true);add('五模型共識 Alpha',selected.map(r=>r._models.formal.consensus.alpha));add('五模型共識 Selection',selected.map(r=>r._models.formal.consensus.selection));add('模型分歧',selected.map(r=>r._models.formal.consensus.divergence));add('五因子',[],true);for(const [k,l] of Object.entries(FACTORS))add(l,selected.map(r=>factor(r,k)));add('Momentum / Risk',[],true);add('價格 Momentum',selected.map(r=>r._momentum));add('3M',selected.map(r=>r.momentum?.ret_3m),false,pct);add('6M',selected.map(r=>r.momentum?.ret_6m),false,pct);add('12M',selected.map(r=>r.momentum?.ret_12m),false,pct);add('Risk Score',selected.map(r=>r.risk?.risk_score));add('估值',[],true);add('估值方法',selected.map(r=>valuationMethod(r)),false,x=>esc(x));add('估值狀態',selected.map(r=>r.valuation?.status||'—'),false,x=>esc(x));const head=`<tr><th>比較項目</th>${selected.map(r=>`<th data-ticker="${r.ticker}">${r.ticker}<span class="subtext">${esc(r.company)}</span></th>`).join('')}</tr>`;const body=rows.map(row=>{if(row.section)return `<tr><td class="compare-section" colspan="${selected.length+1}">${row.label}</td></tr>`;const nums=row.vals.map(Number);const bestIdx=nums.every(Number.isFinite)?nums.indexOf(Math.max(...nums)):-1;return `<tr><td>${row.label}</td>${row.vals.map((v,i)=>`<td class="${i===bestIdx?'compare-best':''}">${row.fmt(v)}</td>`).join('')}</tr>`}).join('');$('#compareContent').innerHTML=`<div class="table-wrap" style="max-height:none"><table class="compare-table"><thead>${head}</thead><tbody>${body}</tbody></table></div>`}
function renderHistory(){const s=state.snapshot;$('#historyContent').innerHTML=`<div class="history-banner"><h2>目前只有 1 個正式 Market Snapshot</h2><p>目前公開正式資料為 ${esc(s.market_key)} R${s.snapshot_revision}。依 V1.21/V1.22 契約，同一 Market Key 的 Revision 只更新當日正式結果，不新增歷史日期；因此現在不使用舊 Demo History 或 XLSX 修改時間製造假趨勢。</p></div><article class="panel"><div class="panel-head"><div><h2>Official Snapshot Timeline</h2><p>歷史軸 = Market Key</p></div>${pillStatus(s.status==='OFFICIAL'?'READY':'UNRESOLVED')}</div><div class="timeline"><div class="timeline-row"><div class="timeline-date">${esc(s.market_key)}</div><div class="timeline-line"><i></i></div><div class="timeline-info">R${s.snapshot_revision} · ${s.model_resolved}/${state.records.length} resolved</div></div></div></article><article class="panel"><div class="panel-head"><div><h2>本次更新</h2><p>沒有上一個 Official Market Key 可做可信差異比較</p></div></div><div class="audit-list"><div class="audit-row"><span>READY</span><b>${s.model_ready}</b><b>目前</b></div><div class="audit-row"><span>NOT_DUE</span><b>${s.model_not_due}</b><b>${state.records.filter(r=>modelStatus(r)==='NOT_DUE').map(r=>r.ticker).join('、')}</b></div><div class="audit-row"><span>UNRESOLVED</span><b>${s.model_unresolved}</b><b>0 blockers</b></div></div></article>`}
function renderAudit(){const rs=state.records,s=state.snapshot;$('#auditMetrics').innerHTML=[metric('Publish Ready',String(s.publish_ready).toUpperCase(),'Official Snapshot'),metric('Resolved',`${s.model_resolved}/${rs.length}`,'Active Universe'),metric('Web Complete',`${s.web_complete}/${rs.length}`,'public contract'),metric('Risk Ready',`${rs.filter(r=>r.risk?.status==='READY').length}/${rs.length}`,'REPORT ONLY'),metric('Valuation Ready',`${rs.filter(r=>r.valuation?.status==='READY').length}/${rs.length}`,'current methods')].join('');$('#auditSources').innerHTML=state.manifest.sources.map(x=>`<div class="audit-row"><span>${esc(DATASET_LABEL[x.dataset]||x.dataset)}</span><b>${esc(x.freshness_status||'—')}</b><b>${finite(x.coverage)?Math.round(x.coverage*100)+'%':'—'}</b></div>`).join('');const cov=[['獲利能力',rs.filter(r=>finite(factor(r,'profitability'))).length],['財務穩健',rs.filter(r=>finite(factor(r,'financial_strength'))).length],['前瞻成長',rs.filter(r=>finite(factor(r,'forward_growth'))).length],['盈餘修正',rs.filter(r=>finite(factor(r,'earnings_revision'))).length],['相對估值',rs.filter(r=>finite(factor(r,'valuation'))).length],['Momentum Score Eligible',rs.filter(r=>finite(r._momentum)).length],['Risk 90D',rs.filter(r=>r.risk?.status==='READY').length]];$('#auditCoverage').innerHTML=cov.map(([l,c])=>`<div class="audit-row"><span>${l}</span><b>${c}/${rs.length}</b><b>${(c/rs.length*100).toFixed(1)}%</b></div>`).join('')}
function openDetail(t){const r=state.records.find(x=>x.ticker===t);if(!r)return;const modelRows=Object.entries(MODELS).map(([k,m])=>`<div class="model-detail-row"><b>${m.zh}</b><div class="bar"><i style="width:${Math.max(0,Math.min(100,r._models.formal[k].selection))}%"></i></div><span>A ${n(r._models.formal[k].alpha)}</span><strong>S ${n(r._models.formal[k].selection)}</strong></div>`).join('');$('#detailContent').innerHTML=`<span class="kicker">${esc(industry(r))} · ${esc(sector(r))}</span><div class="detail-ticker">${esc(r.ticker)}</div><div class="detail-company">${esc(r.company)}</div>${pillStatus(modelStatus(r))}<div class="detail-section"><h3>五模型</h3>${modelRows}<div class="note-box">五模型共識 Selection ${n(r._models.formal.consensus.selection)} · 模型分歧 ${n(r._models.formal.consensus.divergence)}。Selection 仍維持 Financial Alpha 70% + Price Momentum 30%。</div></div><div class="detail-section"><h3>五個底層因子</h3><div class="detail-grid">${Object.entries(FACTORS).map(([k,l])=>`<div class="detail-box"><span>${l}</span><b>${n(factor(r,k))}</b></div>`).join('')}<div class="detail-box"><span>價格 Momentum</span><b>${n(r._momentum)}</b></div></div></div><div class="detail-section"><h3>價格與 Risk</h3><div class="detail-grid"><div class="detail-box"><span>3M</span><b>${pct(r.momentum?.ret_3m)}</b></div><div class="detail-box"><span>6M</span><b>${pct(r.momentum?.ret_6m)}</b></div><div class="detail-box"><span>12M</span><b>${pct(r.momentum?.ret_12m)}</b></div><div class="detail-box"><span>Risk Score</span><b>${n(r.risk?.risk_score)}</b></div><div class="detail-box"><span>90D Vol</span><b>${finite(r.risk?.std_dev_90d)?pct(r.risk.std_dev_90d*100):'—'}</b></div><div class="detail-box"><span>Downside Dev</span><b>${finite(r.risk?.downside_dev_90d)?pct(r.risk.downside_dev_90d*100):'—'}</b></div></div></div><div class="detail-section"><h3>相對估值方法</h3><div class="detail-grid"><div class="detail-box"><span>Current Forward P/E</span><b>${finite(r.valuation?.current_forward_pe)?n(r.valuation.current_forward_pe,2)+'x':'—'}</b></div><div class="detail-box"><span>EV/EBITDA TTM</span><b>${finite(r.valuation?.ev_ebitda)?n(r.valuation.ev_ebitda,2)+'x':'—'}</b></div></div><div class="note-box">正式估值方法：${esc(valuationMethod(r))}<br>${esc(r.valuation?.reason||'')}</div></div><div class="detail-section"><h3>跨產業可比尺度</h3><div class="detail-grid"><div class="detail-box"><span>可比 Alpha</span><b>${n(r._models.comparable.consensus.alpha)}</b></div><div class="detail-box"><span>可比 Selection</span><b>${n(r._models.comparable.consensus.selection)}</b></div><div class="detail-box"><span>可比分歧</span><b>${n(r._models.comparable.consensus.divergence)}</b></div></div></div>`;$('#detailDrawer').classList.add('open');$('#detailBackdrop').classList.add('open');$('#detailDrawer').setAttribute('aria-hidden','false')}
function closeDetail(){$('#detailDrawer').classList.remove('open');$('#detailBackdrop').classList.remove('open');$('#detailDrawer').setAttribute('aria-hidden','true')}
function compareSuggest(){const q=$('#compareSearch').value.trim().toLowerCase();if(!q){$('#compareSuggest').innerHTML='';return}const arr=state.records.filter(r=>!state.compare.includes(r.ticker)&&`${r.ticker} ${r.company} ${industry(r)}`.toLowerCase().includes(q)).slice(0,8);$('#compareSuggest').innerHTML=arr.map(r=>`<div class="suggest-row" data-add="${r.ticker}"><span><b>${r.ticker}</b> · ${esc(r.company)}</span><span>${esc(industry(r))}</span></div>`).join('')}
function commandMatches(){const q=$('#commandInput').value.trim().toLowerCase(),exactTicker=q&&state.records.some(r=>r.ticker.toLowerCase()===q);return state.records.filter(r=>!q||(exactTicker?r.ticker.toLowerCase()===q:`${r.ticker} ${r.company} ${industry(r)}`.toLowerCase().includes(q))).slice(0,12)}
function renderCommand(){const arr=commandMatches();state.commandIndex=Math.min(state.commandIndex,Math.max(0,arr.length-1));$('#commandResults').innerHTML=arr.map((r,i)=>`<div class="command-row ${i===state.commandIndex?'sel':''}" data-command="${r.ticker}"><div><b>${r.ticker} · ${esc(r.company)}</b><small>${esc(industry(r))}</small></div><span>${n(r._models.formal.consensus.selection)}</span></div>`).join('')}
function openCommand(){state.commandIndex=0;$('#command').classList.remove('hidden');$('#commandInput').value='';renderCommand();setTimeout(()=>$('#commandInput').focus(),0)}function closeCommand(){$('#command').classList.add('hidden')}
function exportCSV(){const arr=rankingData();const header=['Rank','Ticker','Company','Industry','Alpha','Momentum','Selection','Model Divergence','Status'];const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const lines=[header.map(q).join(',')];arr.forEach(x=>lines.push([x.rank,x.ticker,x.company,x.industry,x.alpha,x.momentum,x.selection,x.divergence,x.status].map(q).join(',')));const b=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`ForwardAlpha_Rankings_${state.snapshot.market_key}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function bind(){ $$('#mainNav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));document.addEventListener('click',e=>{const row=e.target.closest('[data-ticker]');if(row&&!e.target.closest('#compareContent')&&!e.target.closest('#detailDrawer'))openDetail(row.dataset.ticker);const add=e.target.closest('[data-add]');if(add){if(state.compare.length<4)state.compare.push(add.dataset.add);$('#compareSearch').value='';$('#compareSuggest').innerHTML='';renderCompare()}const rem=e.target.closest('[data-remove]');if(rem){state.compare=state.compare.filter(t=>t!==rem.dataset.remove);renderCompare()}const cmd=e.target.closest('[data-command]');if(cmd){closeCommand();openDetail(cmd.dataset.command)}});$('#detailClose').onclick=closeDetail;$('#detailBackdrop').onclick=closeDetail;$('#rankSearch').oninput=e=>{state.rank.query=e.target.value;renderRankings()};$('#rankModel').onchange=e=>{state.rank.model=e.target.value;renderRankings()};$('#rankScale').onchange=e=>{state.rank.scale=e.target.value;renderRankings()};$('#rankStatus').onchange=e=>{state.rank.status=e.target.value;renderRankings()};$('#rankIndustry').onchange=e=>{state.rank.industry=e.target.value;renderRankings()};$('#rankReset').onclick=()=>{state.rank={query:'',model:'consensus',scale:'formal',status:'ALL',industry:'ALL',sort:'rank',dir:1};$('#rankSearch').value='';$('#rankModel').value='consensus';$('#rankScale').value='formal';$('#rankStatus').value='ALL';$('#rankIndustry').value='ALL';renderRankings()};$$('.data-table th[data-sort]').forEach(th=>th.onclick=()=>{const k=th.dataset.sort;if(state.rank.sort===k)state.rank.dir*=-1;else state.rank={...state.rank,sort:k,dir:['ticker','company','industry'].includes(k)?1:k==='rank'?1:-1};renderRankings()});$('#rankCsv').onclick=exportCSV;$('#modelLabSelect').onchange=renderModelLab;$('#compareSearch').oninput=compareSuggest;$('#globalSearchBtn').onclick=openCommand;$('#commandInput').oninput=()=>{state.commandIndex=0;renderCommand()};$('#command').onclick=e=>{if(e.target.id==='command')closeCommand()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand();return}if(e.key==='Escape'){closeDetail();closeCommand()}if(!$('#command').classList.contains('hidden')){const arr=commandMatches();if(e.key==='ArrowDown'){e.preventDefault();state.commandIndex=Math.min(state.commandIndex+1,arr.length-1);renderCommand()}else if(e.key==='ArrowUp'){e.preventDefault();state.commandIndex=Math.max(0,state.commandIndex-1);renderCommand()}else if(e.key==='Enter'&&arr[state.commandIndex]){e.preventDefault();closeCommand();openDetail(arr[state.commandIndex].ticker)}}})}
async function init(){try{const [payload,snapshot,manifest]=await Promise.all([loadSiteData(),load('data/snapshot_manifest.json'),load('data/source_manifest.json')]);state.snapshot=snapshot;state.manifest=manifest;const decoded=decodeSitePayload(payload,snapshot);state.data=decoded.data;state.official=decoded.official;const universe=state.data.records?.length||0;if(!universe||!state.data.publish_ready||state.data.web_complete!==universe||state.data.model_unresolved!==0)throw new Error('正式資料未通過 Active Universe Web Gate');state.records=state.data.records;enrich(state.records,state.official);document.querySelectorAll('[data-universe-count]').forEach(el=>el.textContent=state.records.length);document.querySelectorAll('[data-tech-count]').forEach(el=>el.textContent=state.records.filter(isTechnology).length);document.querySelectorAll('[data-outside-count]').forEach(el=>el.textContent=state.records.filter(r=>!isTechnology(r)).length);fillControls();renderOverview();renderRankings();renderPool('technology');renderPool('outside');renderModels();renderCompare();renderHistory();renderAudit();bind();document.documentElement.dataset.ready='true'}catch(err){console.error(err);document.body.innerHTML=`<main style="max-width:760px;margin:70px auto;font-family:sans-serif"><h1>網站資料載入失敗</h1><p>${esc(err.message)}</p></main>`;document.documentElement.dataset.ready='error'}}
init();
